### ISSUE TITLE
P2

### ISSUE THREAD

**Issue by pujiaxun** [Snaill123/web_tasks#1]
> 我想请问后续深入的学习爬虫的话应该要从哪些方面继续深入呢？学习的过程中有哪些注意点呢？求学长赐教啊。

关于这个问题啊，继续学习的话，比如考虑爬虫性能，分布式啊之类的。不过初期一般还是以兴趣驱动，需要爬什么，爬完如何处理比较重要，性能可以之后再考虑。往后的话可能会遇到反爬虫机制啊，要想办法对抗之。不过我也没写过多少爬虫，只是业余兴趣，意见只能给到这啦～

**Comment by Snaill123** [comment]
多谢学长啦~~~

**Comment by pujiaxun** [comment]
😁
